# Set the root directory to watch
root = "."
tmp_dir = "tmp"

# Configure the build process
[build]
cmd = "go build -buildvcs=false -o ./tmp/main . || echo 'Build failed'"
bin = "./tmp/main"
delay = 2000
kill_delay = 500
log = "air.log"
full_bin = "APP_ENV=dev ./tmp/main"

[log]
color = true
time = true
level = "debug
