version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      AIR_ENV: development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: league
      POSTGRES_DB_SCHEMA: league_management
      DB_CONNECTION_STRING: postgres://root:root@localhost:5432/league?sslmode=disable
    command: air
    networks:
      - app-network
    depends_on:
      - db
    restart: always

#  prod:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: prod
#    ports:
#      - "8080:8080"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
